declare module 'lucide-react' {
  import * as React from 'react';
  export const Bell: React.ComponentType<any>;
  export const CircleHelp: React.ComponentType<any>;
  export const Search: React.ComponentType<any>;
  export const HelpCircle: React.ComponentType<any>;
  export const Mic: React.ComponentType<any>;
  export const Volume2: React.ComponentType<any>;
  export const Copy: React.ComponentType<any>;
  export const Phone: React.ComponentType<any>;
  export const Settings: React.ComponentType<any>;
    export const Users: React.ComponentType<any>;
    export const Sparkles: React.ComponentType<any>;
  export const Play: React.ComponentType<any>;
  export const CheckCircle: React.ComponentType<any>;
  export const CheckCircle2: React.ComponentType<any>;
  export const Lightbulb: React.ComponentType<any>;
  export const GraduationCap: React.ComponentType<any>;
  export const User: React.ComponentType<any>;
  export const Mail: React.ComponentType<any>;
  export const AtSign: React.ComponentType<any>;
  export const Lock: React.ComponentType<any>;
  export const ChevronDown: React.ComponentType<any>;
  export const Briefcase: React.ComponentType<any>;
  export const X: React.ComponentType<any>;
  export const Clock: React.ComponentType<any>;
  export const Zap: React.ComponentType<any>;
  export const Trophy: React.ComponentType<any>;
  export const Code: React.ComponentType<any>;
  export const Shield: React.ComponentType<any>;
  export const Monitor: React.ComponentType<any>;
  export const Building2: React.ComponentType<any>;
  export const Calendar: React.ComponentType<any>;
  export const ArrowRight: React.ComponentType<any>;
  export const Plus: React.ComponentType<any>;
  export const SlidersHorizontal: React.ComponentType<any>;
  export const ArrowUpDown: React.ComponentType<any>;
  export const TrendingUp: React.ComponentType<any>;
  const _default: { [key: string]: React.ComponentType<any> };
  export default _default;
}
